### ISSUE TITLE
sports4u.tv links issue

### ISSUE THREAD

**Issue by KBug** [harddevelop/tvbox#2]
Most of the links for the sports4u.tv aren't working. A few briefly showed the stream and then closed. Some links did nothing and some links gave a message that the link appears to be down. Hard to tell what the problem might be with getting a variety of results. The links are working on the sports4u.tv website. For example Fox Sports 1 does nothing when selecting it and BT Sports ESPN gives an error message the link must be down, but both of those were working on the website.

**Comment by bitstuffing** [comment]
Parser is now finished for all subpages.
There was an issue related to domain. 
A simple change was done and all was working fine.
